version: '3.9'

services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  ui:
    build: ./ui
    ports:
      - "3000:3000"

  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: